<Project>
	
	<Target Name="GenerateBuildInfo" BeforeTargets="CoreCompile" Condition="'$(CreatePackage)' == 'true' OR '$(IsPatcher)' == 'true'">
    <PropertyGroup Condition="'$(IsPatcher)' == 'true'">
      <DefinePatcherConstant>#define PATCHER</DefinePatcherConstant>
    </PropertyGroup>
		<PropertyGroup>
			<VersionNumber>$(Version.Split('-')[0])</VersionNumber>
			<BuildInfoFile>$(IntermediateOutputPath)BuildInfo.cs</BuildInfoFile>
			<ClassName>$([System.Text.RegularExpressions.Regex]::Match('$(RootNamespace)', '[^.]+$').Value)</ClassName>
			<MyTextLines>
$(DefinePatcherConstant)

namespace $(RootNamespace)%3B

#if !PATCHER
[BepInEx.BepInPlugin(PluginGuid, PluginName, PluginVersion)]
#endif
public sealed partial class $(ClassName)Plugin
{
  public const string Author = "$(Authors)"%3B
	public const string PluginName = "$(MSBuildProjectName)"%3B
	public const string PluginGuid = $"{Author}.{PluginName}"%3B
	public const string PluginVersion = "$(VersionNumber)"%3B
	public const string PluginInformationalVersion = "$(Version)"%3B
	DateTimeOffset BuildTimestamp { get%3B } = new($([System.DateTimeOffset]::UtcNow.UtcTicks), default)%3B
  
#if DEBUG
  internal const string DependencyDirectory = @"$(DependencyDirectory)"%3B
#endif
	
#if !PATCHER
	void Awake()
	{
    if (PluginVersion != PluginInformationalVersion)
      Logger.LogWarning($"You are running a pre-release version: {PluginInformationalVersion} ({BuildTimestamp.LocalDateTime})")%3B
		OnAwake()%3B
	}
	
	partial void OnAwake()%3B
#endif
}
			</MyTextLines>
		</PropertyGroup>

		<WriteLinesToFile File="$(BuildInfoFile)" Overwrite="true" Lines="$(MyTextLines)" />

		<ItemGroup>
			<Compile Include="$(BuildInfoFile)" />
		</ItemGroup>
	</Target>

	<Target Name="CreatePackage" AfterTargets="AfterBuild" Condition="'$(CreatePackage)' == 'true'">
		<ItemGroup>
			<Dependencies Include="@(ProjectReference)" Condition="'%(ProjectReference.OutputItemType)' == ''" />
		</ItemGroup>
		
		<MSBuild Projects="@(Dependencies)" Targets="GetTargetPath">
			<Output TaskParameter="TargetOutputs" ItemName="DependencyPaths" />
		</MSBuild>

		<Exec Command='pwsh -ExecutionPolicy Bypass -File "$(MSBuildThisFileDirectory)Create-Package.ps1" -Path "$(TargetPath)" -Url "$(RepositoryUrl)" -Description "$(Description)" -Dependencies "@(DependencyPaths)" -StoreDependencies "@(StoreDependencies)" -Destination "$(MSBuildThisFileDirectory)plugins\$(Configuration)\$(MSBuildProjectName).zip"' />
	</Target>

</Project>