<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Configure various aspects around tameable creatures. Allow all tames to follow you, even through portals and into dungeons. Show taming and growing up/hatching progress to nearby players.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServersideQoL\ServersideQoL.csproj" Private="False" />
    <ProjectReference Include="..\ServersideQoL.ContainerSigns\ServersideQoL.ContainerSigns.csproj" Aliases="ContainerSigns" Private="False" PrivateAssets="all" OutputItemType="Analyzer" />
  </ItemGroup>

</Project>
