<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Serverside-only QoL mod, compatible with vanilla/console (e.g. XBox, PS, Switch) clients. Stack player inventories into chests, generated portal hub, auto-sort chests, refuel smelters from containers, infinite building/farming stamina and much more</Description>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <StoreDependencies Include="denikson-BepInExPack_Valheim-5.4.2350" />
    <StoreDependencies Include="ValheimModding-YamlDotNet-16.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServersideQoL.Patchers\ServersideQoL.Patchers.csproj" PrivateAssets="all" OutputItemType="Analyzer" />
  </ItemGroup>

</Project>
