<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Resurrect your fallen friends and let them rise from the ashes of defeat and despair</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServersideQoL\ServersideQoL.csproj" Private="False" />
  </ItemGroup>

</Project>
